import type {DemoState,Farm,Role} from './domain';
export const regions=['Himalayan Giants','Dooars Tuskers','Cooch Behar Royals','Dinajpur Defenders','Malda Kings','Murshidabad Nawabs','Nadia Warriors','Bardhaman Krishi Kings','Hooghly Harits','Birbhum Blasters','Bankura Bulls','Purulia Panthers','Medinipur Mavericks','Ganga Gladiators','Sundarban Strikers'];
const districts=['Darjeeling','Jalpaiguri','Cooch Behar','Uttar Dinajpur','Malda','Murshidabad','Nadia','Purba Bardhaman','Hooghly','Birbhum','Bankura','Purulia','Paschim Medinipur','Howrah','South 24 Parganas'];
const crops=['Aman rice','Mustard','Potato','Jute','Mango','Tea','Vegetables']; const names=['Ananya','Arup','Mita','Ritwik','Poulomi','Sayan'];
const uuid=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export function seed():DemoState{const farms:Farm[]=Array.from({length:5292},(_,i)=>{const r=i%15;const special=i===86;const score=special?82.4:Math.round((52+(i*17)%410/10)*10)/10;return{id:uuid(i+1),passportId:special?'KRL-WB-23-087':`KRL-WB-${String((i%294)+1).padStart(3,'0')}-${String(i+1).padStart(4,'0')}`,farmer:special?'Asha D. (demonstration)':`${names[i%names.length]} ${String.fromCharCode(65+i%20)}.`,region:regions[r],district:districts[r],constituency:`Constituency ${(i%294)+1}`,village:special?'Haripur cluster':'Village cluster',type:i%3===0?'Integrated':i%3===1?'Smallholder':'Horticulture',crop:crops[i%crops.length],enterprises:i%3===0?['Crops','Fishery','Livestock']:['Crops'],status:i%17===0?'At risk':'Active',score,baseline:Math.max(20,score-18),verified:i%5!==0,lat:22.57+(r-7)*.105+((i*13)%100)/900,lng:88.36+(r-7)*.115+((i*7)%100)/900,lastUpdate:'2026-09-18',mentor:`Mentor ${(i%10)+1}`,openIssues:i%7===0?1:0,pillars:{Satya:score-3,Mangal:score+2,Sundar:score-1,Samriddhi:score+1}}});const showcase=farms[86];return{farms,visits:25,approved:[],activities:[{id:'a1',farmId:showcase.id,kind:'Evidence verified',summary:'Water harvesting structure verified',date:'2026-09-18'},{id:'a2',farmId:showcase.id,kind:'Progress update',summary:'Second crop cycle completed',date:'2026-09-12'},{id:'a3',farmId:showcase.id,kind:'Mentor visit',summary:'Soil health and record keeping review',date:'2026-09-04'}]}}
const KEY='krl-demo-v1';
export const repo={load():DemoState{const raw=localStorage.getItem(KEY);if(raw)try{return JSON.parse(raw) as DemoState}catch{localStorage.removeItem(KEY)}const s=seed();this.save(s);return s},save(s:DemoState){localStorage.setItem(KEY,JSON.stringify(s))},reset(){localStorage.removeItem(KEY);return this.load()},progress(farmId:string,data:{summary:string;kpi:number}){const s=this.load(),f=s.farms.find(x=>x.id===farmId)!;f.score=Math.round(Math.min(100,f.score+(data.kpi-f.score)*.08)*10)/10;f.lastUpdate=new Date().toISOString().slice(0,10);s.activities.unshift({id:crypto.randomUUID(),farmId,kind:'Progress update',summary:data.summary,date:f.lastUpdate});this.save(s);return s},visit(farmId:string,summary:string){const s=this.load();s.visits++;s.activities.unshift({id:crypto.randomUUID(),farmId,kind:'Mentor visit',summary,date:new Date().toISOString().slice(0,10)});this.save(s);return s},approve(farmId:string){const s=this.load(),f=s.farms.find(x=>x.id===farmId)!;f.verified=true;if(!s.approved.includes(farmId))s.approved.push(farmId);s.activities.unshift({id:crypto.randomUUID(),farmId,kind:'Score approved',summary:'Final score approved and added to ranking',date:new Date().toISOString().slice(0,10)});this.save(s);return s}};
export const demoUsers:Record<string,{name:string;role:Role;description:string}>={admin:{name:'Command Centre Admin',role:'Super Admin',description:'Statewide operations, scoring and configuration'},regional:{name:'Regional Manager',role:'Regional Manager',description:'Regional farms, teams and issues'},mentor:{name:'KRL Mentor',role:'Mentor',description:'Visits, evidence and progress'},judge:{name:'Season Judge',role:'Judge',description:'Evidence review and score approval'}};
